### ISSUE TITLE
Includes content included twice in distill article

### ISSUE THREAD

**Issue by mattwarkentin** [rstudio/distill#279] opened 2021-01-02 18:20 UTC
Hi,

When including additional HTML content via the `includes` YAML option, it appears as though the content is included twice over. Here is some code to help reproduce...
```yaml
# _site.yml
name: "test-website"
title: "Name"
description: |
  Placeholder
output_dir: "docs"
navbar:
  right:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
output:
  distill::distill_article:
    toc: true
    includes:
      before_body: include.html
      after_body: include.html
```

### include.html
```html
<p>Test</p>

```

And here is the result...
<img width="1280" alt="Screen Shot 2021-01-02 at 1 18 42 PM" src="https://user-images.githubusercontent.com/27825069/103463788-194f5b00-4cfd-11eb-9d34-cb3d28f979de.png">

**Comment by apreshill** [comment] 2021-01-02 21:25
Hi there! Just so I understand, I would expect what you are seeing here since `include.html` seems to be inserted twice- once before and after the body, correct? Can you say more about what you would expect here?

```
output:
  distill::distill_article:
    toc: true
    includes:
      before_body: include.html <- first
      after_body: include.html    <- second
```

**Comment by mattwarkentin** [comment] 2021-01-02 23:10
Hi @apreshill,

It's hard to see but `<p>Test<p/>` is shown twice for each - two are sorta hidden underneath the nav bar (`before_body`), and twice again at the end of the document (`after_body`). It is easier to confirm when using developer tools in Chrome, for example.

**Comment by jjallaire** [comment] 2021-01-03 13:30
I can see this as well. Thanks for reporting, we'll take a look and hopefully fix this ASAP!

**Comment by apreshill** [comment] 2021-01-03 13:46
Ah I see it up top now! Thanks for catching that!

**Comment by jjallaire** [comment] 2021-01-03 14:10
Should be fixed here: https://github.com/rstudio/distill/commit/0f03ee67452b05bf37367c1331e07944cdb3ade0

**Comment by jjallaire** [comment] 2021-01-04 01:24
The fix for this caused a regression, see https://github.com/rstudio/distill/commit/0f03ee67452b05bf37367c1331e07944cdb3ade0

**Comment by jjallaire** [comment] 2021-01-04 11:10
Hopefully fixed for good here: https://github.com/rstudio/distill/commit/c272438210377d1e7b0e05a974c60055bc5d8453

**Closed by jjallaire** 2021-01-04 11:10 UTC
