### ISSUE TITLE
Consider downlit for syntax highlighting and automatic linking  

### ISSUE THREAD

**Issue by apreshill** [rstudio/distill#165] opened 2020-09-19 01:41 UTC
https://github.com/r-lib/downlit

+ Would need a fall-back for code highlighters for non-R code

+ A happy side-effect would be automated cross-package links to help docs

**Comment by jjallaire** [comment] 2020-09-19 01:46
Already done!

There are a couple of loose ends though:

1) We currently use the `haddock` pandoc syntax highlighting theme. I'd like to replace this with a custom theme derived from the RStudio textmate theme.

2) Want to do some subtle coloring of linked functions so it's more obvious that they are clickable (will have to experiment a bit to get it right).

Will leave this issue open until these things get sorted out.

**Comment by apreshill** [comment] 2020-09-19 01:58
Sounds good. Actually the current highlighting theme was one of the things that is throwing up Accessibility warnings (according to: https://github.com/dequelabs/axe-core). If there is any freedom from the syntax highlighting themes available via pandoc, every single one of them results in a low contrast warning. I did a deep dive into these awhile back, and found this: 
https://github.com/ericwbailey/a11y-syntax-highlighting

I'm not sure how the RStudio textmate theme fares accessibility-wise, but I've been unsatisfied with the range of pandoc syntax highlighters for this reason.

**Comment by jjallaire** [comment] 2020-09-19 11:34
Some follow up:

1) The RStudio-compatible highlighting is checked in (some enhancements to this may still occur, see https://github.com/r-lib/downlit/issues/57)

2) It is possible to use a fully custom theme by executing this:

```bash
 pandoc --print-highlight-style pygments > custom.theme
```

Then editing the custom.theme file until you get the look you want. This can be fed to distill via:

```yaml
---
output:
  distill::distill_article: 
    highlight: custom.theme
---
```

So if you come up with a more accessibility friendly theme we could make it more generally available. 

One possible hitch though: It looked to me like the themes defined in https://github.com/ericwbailey/a11y-syntax-highlighting had a non-white background? That currently won't work w/ distill b/c code chunks are purposely allowed to overflow the main column to the right (and if you have a background color it only spans the main text column). To have a background color I think we'd need to allow it to span the entire width of the page, not sure how that would end up looking. I may be wrong about this though and a non-white background isn't required after all. LMK what you find out.

**Comment by apreshill** [comment] 2020-09-19 11:37
Thank you! I'll look into that. Do you think the light mode would work?
![a11y-light](https://user-images.githubusercontent.com/12160301/93666276-fac59c80-fa4a-11ea-8a90-b868f7bbadc9.png)

https://github.com/ericwbailey/a11y-syntax-highlighting/blob/main/images/a11y-light.png

**Comment by jjallaire** [comment] 2020-09-19 11:59
Yes definitely! We won't even need to change the background (since by default pandoc light themes have no background). LMK once you get a prototype of this working and we can integrate it as another highlighting option. 

Note that we should also be able to get this to work more generally for rmarkdown (i.e. any format that calls `pandoc_highlight_args()`).

**Comment by jjallaire** [comment] 2020-09-19 12:01
I haven't yet come up with an elegant way to highlight linked functions. The problem is that they aren't really different syntactically from non-linked functions, so giving them a different color looks odd. I think we will probably just have to rely on the mouse-over underline effect to tip users off.

**Comment by jjallaire** [comment] 2020-09-19 14:09
Updated docs on syntax highlighting here: https://rstudio.github.io/distill/#syntax-highlighting

**Comment by jjallaire** [comment] 2020-09-20 12:23
Closing this one (will create a new issue for the addition of an accessible custom theme)

**Closed by jjallaire** 2020-09-20 12:23 UTC
Labels: feature request :mount_fuji:
