### ISSUE TITLE
For include_graphics, out.width ignored when fig.cap is set

### ISSUE THREAD

**Issue by ssp3nc3r** [rstudio/distill#286] opened 2021-01-07 15:22 UTC
For use of `knitr::include_graphics`: without a figure caption, an image width can be specified by `out.width`,

````
```{r, out.width="50%"}
knitr::include_graphics("image.png")
```
````

but `out.width` is ignored and uses 100% when `fig.cap` is used:

````
```{r, out.width="50%", fig.cap="Test"}
knitr::include_graphics("image.png")
```
````

Distill version 1.1.2, GithubSHA1: e53e8ff1e5608231eace6264df4a33a1b81f2876

**Comment by apreshill** [comment] 2021-01-13 14:23
I can confirm I am seeing this too, not only with include graphics but any figures produced with R code, and not in a bookdown project.

<img width="1421" alt="Screen Shot 2021-01-13 at 9 14 27 AM" src="https://user-images.githubusercontent.com/12160301/104463737-259aaa00-5580-11eb-85af-310dcd86cab7.png">


<img width="1421" alt="Screen Shot 2021-01-13 at 9 14 33 AM" src="https://user-images.githubusercontent.com/12160301/104463753-27fd0400-5580-11eb-8225-7a424232ffa8.png">

https://github.com/apreshill/knitrfigcap

**Comment by jhelvy** [comment] 2021-03-05 13:41
I'm seeing the same problem. My temporary fix is to use markdown syntax to insert an image (obviously doesn't work with rendered plots):

```r
![Insert caption text](images/image.png){width=80%}
```

But this solution doesn't allow me to align the image (e.g. left, center, right). It's always left-justified.

**Comment by jhelvy** [comment] 2021-07-06 10:36
Just noting that I think this has been fixed in v1.2. Images resize now with figure captions according to the `out.width` settings.

**Comment by cderv** [comment] 2021-07-06 11:34
@jhelvy I don't think this has been fixed. Can you share a small example that works for you ? 
This one above still don't: https://github.com/rstudio/distill/issues/286#issuecomment-759481165

````markdown
```{r nice-fig, fig.asp=.75, fig.align='center'}
par(mar = c(4, 4, .1, .1))
plot(pressure, type = 'b', pch = 19)
```

```{r ref.label="nice-fig", out.width="50%"}
```

```{r ref.label="nice-fig", fig.cap='Here is a nice figure!', out.width="50%"}
```
````

This is the HTML code that is outputed for the second plot 

````html
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-2"></span>
<img src="test_files/figure-html5/unnamed-chunk-2-1.png" alt="Here is a nice figure!" width="50%" style="max-width: 100%;">
<p class="caption">
Figure 1: Here is a nice figure!
</p>
</div>
````

The issue comes from the fact that **knitr** currently behave this way: 

* when `fig.cap` is used, a figure environment is created using `<div class="figure">` (and not `<figure>`) 
* `<img>` and `<p class="caption">` are put in this div. 
* **distill** applies a specific css on `.figure img` which takes precedence over the `width` argument in `<img>`
tag 

https://github.com/rstudio/distill/blob/cd7cf53ad0069a4b221baadb1dfedf433723e040/inst/rmarkdown/templates/distill_article/resources/distill.html#L310-L312

This CSS comes from distill and is inserted into the HTML. We need to see how we can tweak it. 

Current workaround would be to override this CSS rule for the chunk to apply `width` using CSS style rule instead of `img` attribute.

**Comment by jhelvy** [comment] 2021-07-07 17:17
After looking again at this, it seems to only be an issue when I define the width as a percentage. When I provide pixel values it works for me. On [this post](https://www.jhelvy.com/posts/2021-07-03-in-search-of-keyboard-nirvana/) I include lots of figures with captions and different widths and they all work (source [here](https://github.com/jhelvy/jhelvy.com/blob/master/_posts/2021-07-03-in-search-of-keyboard-nirvana/in-search-of-keyboard-nirvana.Rmd)).

**Comment by cderv** [comment] 2021-07-07 19:52
Oh interesting ! However, I tried this and it still got me incorrect width
````markdown
---
title: "Untitled"
output: distill::distill_article
---

```{r nice-fig, fig.asp=.75, fig.align='center'}
par(mar = c(4, 4, .1, .1))
plot(pressure, type = 'b', pch = 19)
```

```{r ref.label="nice-fig", out.width="300px"}
```

```{r ref.label="nice-fig", fig.cap='Here is a nice figure!', out.width="300px"}
```

````

Seems like the unit is the key. When removing it as you have done in your source, it works ok. 

````markdown
---
title: "Untitled"
output: distill::distill_article
---

```{r nice-fig, fig.asp=.75, fig.align='center'}
par(mar = c(4, 4, .1, .1))
plot(pressure, type = 'b', pch = 19)
```

```{r ref.label="nice-fig", out.width="300"}
```

```{r ref.label="nice-fig", fig.cap='Here is a nice figure!', out.width="300"}
```
````

I don't know why, but when no unit is passed `width: 300px;` is added into the style attributes of the image, which correct get precedence (re. what I mentioned in earlier comment)

````html
<img src="data:image/png;base64,iVBORw0(...)" alt="Here is a nice figure!" width="300" style="max-width: 100%; width: 300px;">
````

I need to see where this difference in behavior happens. 

However, this is a workaround for this issue.

**Comment by jhelvy** [comment] 2021-07-07 20:36
Yes, I noticed the same behavior. If I included `px` in the width it would not resize appropriately, so I just took it out and it worked. I think a "workaround" is the right thing to call this rather than a fix. It's still something of a bug.

**Comment by cderv** [comment] 2021-07-07 21:00
Oh yes this is still a bug for sure. But your finding is really interesting, I was not aware of this. Thanks to sharing it!

**Closed** 2022-05-11 09:46 UTC
Labels: bug :bug:

**Comment by cderv** [comment] 2022-05-11 09:54
After much thinking and a few tries, I believe the safest things to do here is to remove the CSS rules that is taking precedence and rely only on inline attribute `width=` on `<img>`. We have a specific JS process that handle the layout and chunk image to support other that `l-body`. Hopefully, this will make things much better and aligned with past behavior (https://github.com/rstudio/distill/issues/41)
