### ISSUE TITLE
An update to RStudio version 1.4 with visual editor broke an iframe embed in Distill document

### ISSUE THREAD

**Issue by howardm** [rstudio/distill#314] opened 2021-02-09 01:32 UTC
Hi,

After I upgraded, the following code for an embedded iframe broke:

```
### Testing Pacsbin viewer

Here is text before presentation of the embedded medical image viewer.

```{=html}
<div style="text-align:center;">
<iframe class="pacsbin"
id="vali"
src="https://www.pacsbin.com/c/W1QLNa-iQS?s=5db79e00e55657647bcf5e1f&i=5db79e00e55657647bcf5e20&ww=3601&wc=2560&an=false&overlay=false"
style="width: 500px; height: 500px; border: 0;"></iframe>
<ul class="list-inline list-pipe">
<li><a class="pacsbin-link" href="#vali?s=0">PA Chest</a></li>
<li><a class="pacsbin-link" href="#vali?s=1">Axial CT</a></li>
</ul>
</div>
```
This screenshot shows the result:

___

![Screen Shot 2021-02-08 at 6 05 03 PM](https://user-images.githubusercontent.com/6101226/107301489-d5a4eb00-6a38-11eb-9515-48647e702fb6.jpg)

___

I note the following assertion about using the Visual Editing Mode:

"Visual editing mode generates markdown using Pandoc. This means that in some cases your markdown will be rewritten to conform to standard Pandoc idioms."

I tried that mode for a moment, but am not using it at present. 

In another part of my document, the following code for a video embed is still working:

````
```{=html}
<div style="text-align:center;">
<iframe src="https://player.vimeo.com/video/509914554" style="width: 512px; height: 512px; border: 0;" allowfullscreen></iframe>
</div>
```
````
Can you see what the problem may be ?

Thanks.

Howard

**Comment by storopoli** [comment] 2021-02-10 09:21
@howard try to close the HTML chunk with ```

If that doesn't work. Try inserting the HTML code outside any code chunk just into the plain .Rmd document.

**Comment by cderv** [comment] 2021-02-10 10:26
Hi @howardm, 

RStudio 1.4 comes with a newer Pandoc (2.11.2 I think - you can check with `rmarkdown::pandoc_version()`)

You are encountering this issue: https://github.com/rstudio/rmarkdown/issues/2027

There is [a change in Pandoc that is causing what you are seing](https://github.com/jgm/pandoc/issues/6854) - Pandoc will now also makes iframes self-contained when self contained mode is true - which is the default for **distill** document. Pandoc aims at having document that do not require net access. But for iframes, it could cause issues. 

[The Pandoc way to solve this](https://pandoc.org/MANUAL.html#option--self-contained) is to add the attributes `data-external=1` to your iframe. This will indicate to Pandoc to not encode the content of iframe to DATA URI. 

This works for me 
````markdown
---
title: "Untitled"
date: "`r Sys.Date()`"
output: 
  distill::distill_article: default
---

### Testing Pacsbin viewer

Here is text before presentation of the embedded medical image viewer.

```{=html}
<div style="text-align:center;">
<iframe class="pacsbin"
id="vali"
src="https://www.pacsbin.com/c/W1QLNa-iQS?s=5db79e00e55657647bcf5e1f&i=5db79e00e55657647bcf5e20&ww=3601&wc=2560&an=false&overlay=false"
style="width: 500px; height: 500px; border: 0;" data-external=1></iframe>
<ul class="list-inline list-pipe">
<li><a class="pacsbin-link" href="#vali?s=0">PA Chest</a></li>
<li><a class="pacsbin-link" href="#vali?s=1">Axial CT</a></li>
</ul>
</div>
```
````

Obviously you can also use `self_contained=FALSE` for your document, but you will use the one document only, having the libs in another directory - so that depends on your use case. 

Setting the attributes works well. We are thinking on how to improve this in the future. 

Thanks for the report.

We'll close this one and issue to follow is : https://github.com/rstudio/rmarkdown/issues/2027

**Comment by howardm** [comment] 2021-02-10 16:42
@cderv 

Thank you!

I wonder if this is also the explanation for the following problem I had with a different video embed I mention above:

An embedded Vimeo video would not play and I received the following error message in Firefox:

___

![Screen Shot 2021-02-08 at 6 52 09 PM](https://user-images.githubusercontent.com/6101226/107540376-393b2f80-6b83-11eb-858f-fb174f4aca5f.jpg)

____

A reply from Vimeo included the following:

___

![Screen Shot 2021-02-10 at 9 31 19 AM](https://user-images.githubusercontent.com/6101226/107540572-6e478200-6b83-11eb-97a5-7c0cfc78fa93.jpg)

___

I don't know anything about Referrer, but it would certainly seem to be causally related.

I could update to RStudio version 1.4  (I reverted back to 1.2) and try again.

Howard

**Comment by cderv** [comment] 2021-02-10 16:45
This could definitely be the cause of this issue. I would add the `data-external=1` to any content your embed that would need a net access. iframe are one of them I think.

> I could update to RStudio version 1.4 (I reverted back to 1.2) and try again.

You could also send me the link and I try if you want.

**Comment by howardm** [comment] 2021-02-10 17:03
This is the code for a Vimeo embed:

```{=html}
<div style="text-align:center;">
<iframe src="https://player.vimeo.com/video/510041214" style="width: 512px; height: 512px; border: 0;" allowfullscreen></iframe>
</div>
```
But now I'm learning more about the option of specifying `self_contained = false` in my document. I did that and the knit to HTML happened much (!) faster. Hah! Now I'm beginning to understand why -- embedding all the images/videos in data: URIs, etc.

I didn't realize that `self_contained = true` is the default mode for Distill.

I cannot think of a reason why I should not use `self_contained = false` for my website.

Howard

**Comment by cderv** [comment] 2021-02-10 17:20
I can confirm that adding `data-external=1` on this iframe will make it work in the HTML result. Just tried it.

**Closed** 2021-02-10 21:45 UTC
