### ISSUE TITLE
Justify text

### ISSUE THREAD

**Issue by rpmeira** [rstudio/distill#325] opened 2021-02-24 01:18 UTC
Hi,
I would like to change the text align of my blog posts to justified, but I can't seem to find exactly where in the 'theme.css' I should modify it. Can anyone help me please?

**Comment by werkstattcodes** [comment] 2021-02-24 11:43
try adding this:

d-article p {
    text-align: justify;
}

**Comment by rpmeira** [comment] 2021-02-24 13:46
> try adding this:
> 
> d-article p {
> text-align: justify;
> }

Thanks! it's worked just fine.

**Comment by rpmeira** [comment] 2021-02-25 16:27
> d-article p {
> text-align: justify;
> }

Actually, this has messed with my markdown tables, and I have no idea why. 
For reproducible purpose, try to create a new Distill Blog, insert the table below, Knit it, then make that text-align suggested, then Knit it again. The tables alignment gets messed up.

![Sem título](https://user-images.githubusercontent.com/64609486/109182816-1c4e5100-776c-11eb-87ee-9f8d0fa946c2.png)

It goes from this:
![Sem título3](https://user-images.githubusercontent.com/64609486/109183351-9e3e7a00-776c-11eb-8516-7ee348fbe397.png)

To this:
![Sem título2](https://user-images.githubusercontent.com/64609486/109183375-a4345b00-776c-11eb-8301-543957553d18.png)

Ps. I'd tried to insert the tables' code here, but it got messed up, so I've inserted a picture.

**Comment by cderv** [comment] 2021-02-25 17:34
@rpmeira I can't reproduce this. (with recent version of tools)
````markdown
---
title: "Untitled"
date: "2021-02-12"
output: 
  distill::distill_article
---

```{css, echo = FALSE}
d-article p {
  text-align: justify;
}
```

Some text that should be justified.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
bbbbbbbbbbbbbbbbbbbb.
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa. dddddddddddddddddddddddddddddddddd


### A table

::: {style="display: flex; justify-content: center; line-height: 15px;"}
+------------------------+------------------------+--------------------+
| Header1                | Header2                | Header3            |
+========================+:======================:+:==================:+
| a                      | 1                      | `A`                |
+------------------------+------------------------+--------------------+
| b                      | 2                      | `B`                |
+------------------------+------------------------+--------------------+
| c                      | 3                      | `C`                |
+------------------------+------------------------+--------------------+
:::
```

![image](https://user-images.githubusercontent.com/6791940/109192753-ecb53e00-7797-11eb-9f1e-d7f15b9217d1.png)

I don't think there is an issue with **distill**. This is a question regarding CSS rules, selector and precedance. Stackoverflow and https://community.rstudio.com are great place to ask question like this. 

Do you mind if I close this as it is not an issue with the package ? If you still have issues, I would encourage your to ask on one of the Q&A site above where there are a broad community ready to help.

> PS. I'd tried to insert the tables' code here, but it got messed up, so I've inserted a picture.

You need to add one more backtick if you have codeblock in the example you want to show (https://yihui.org/issue/#please-format-your-issue-correctly)

**Comment by rpmeira** [comment] 2021-02-25 18:05
@cderv  that's Ok. I don't think either this is an issue with distill.
Thanks anyway for trying to reproduce it.

> You need to add one more backtick if you have codeblock in the example you want to show (https://yihui.org/issue/#please-format-your-issue-correctly)

And thanks for the tip.

Regards.

**Comment by cderv** [comment] 2021-02-25 18:23
> Thanks anyway for trying to reproduce it.

Is my example working for you ? 

Don't forget to update the packages too.

**Comment by rpmeira** [comment] 2021-02-25 18:39
> Is my example working for you ?

Yes, it is.
I think the issue has something to do with the way "Visual Markdown Editor" makes the table. 
I've tried to make it myself, and now the table is not getting messed up anymore.

Below I've put the two codes. The first one was gerenated by "Visual Markdown Editor", the second one I've made myself.

````

```{css, echo = FALSE}
d-article p {
  text-align: justify;
}
```

::: {style="display: flex; justify-content: center; line-height: 15px;"}
+----------------------+------------------+---------------------+
|                      | Variável         | Parâmetro           |
+======================+:================:+:===================:+
| **Mercado**          | `Init`           | `alpha` ($\alpha$)  |
|                      |                  |                     |
|                      | `HHI`            | `delta` ($\delta$)  |
|                      |                  |                     |
|                      | `HPI`            | `tau` ($\tau$)      |
|                      |                  |                     |
|                      | `TotProb`        | `Cmin`              |
|                      |                  |                     |
|                      |                  | `Cmax`              |
|                      |                  |                     |
|                      |                  | `C0`                |
|                      |                  |                     |
|                      |                  | `Q0`                |
|                      |                  |                     |
|                      |                  | `N`                 |
+----------------------+------------------+---------------------+
| **Firma**            | `Prob`           |                     |
|                      |                  |                     |
|                      | `Quality(1)`     |                     |
|                      |                  |                     |
|                      | `Convenience(1)` |                     |
|                      |                  |                     |
|                      | `sigma(1)`       |                     |
|                      |                  |                     |
|                      | `ms(1)`          |                     |
+----------------------+------------------+---------------------+
:::

::: {style="display: flex; justify-content: center; line-height: 20px;"}
+----------------+--------------------------+---------------------+
|                | Variável                 | Parâmetro           |
+================+:========================:+:===================:+
| **Mercado**    | `Init`\                  | `alpha` ($\alpha$)\ |
|                | `HHI`\                   | `delta` ($\delta$)\ |
|                | `HPI`\                   | `tau` ($\tau$)\     |
|                | `TotProb`\               | `Cmin`\             |
|                |                          | `Cmax`\             |
|                |                          | `C0`\               |
|                |                          | `Q0`\               |
|                |                          | `N`\                |
+----------------+--------------------------+---------------------+
| **Firma**      | `Prob`\                  |                     |
|                | `Quality(1)`\            |                     |
|                | `Convenience(1)`\        |                     |
|                | `sigma(1)` ($\sigma$)\   |                     |
|                | `ms(1)`\                 |                     |
+----------------+--------------------------+---------------------+
:::
````

Here's the output:

![Sem título](https://user-images.githubusercontent.com/64609486/109200502-76a4dd00-777f-11eb-937b-21850a012e88.png)

**Comment by cderv** [comment] 2021-02-26 08:34
Thanks for sharing.

The difference relies on the line break. In the second table you have _Hard Line Break_. [You need to explicitly insert those in Visual editor using SHIFT + Enter (or the insert menu).](https://rstudio.github.io/visual-markdown-editing/#/content?id=hard-line-breaks) If you add a normale Line Break (ENTER), it will be seen as a new paragraph in the markdown code (the empty line between each element), leading to Pandoc creating a `<p>` for each element in a table cell. 

Look at the HTML produced, you get `<p>` tags in your table after that. So your CSS will apply to it because the CSS selector means "Every \<p> element that are somewhere below a \<d-article> element". This is why the _justify_ will apply to those elements inside the table and will overwrite the centering set because you use the `:------:` syntax in the table column. 

This also happens because [grid tables](https://pandoc.org/MANUAL.html#extension-grid_tables) is used. Which the visual editor use because you need to use some markdown element in your table (like code and latex I believe)

Anyway, if you take care of this while writing your table in visual editor, it will produce the correct table in markdown source. 

You can also change the CSS rule to use a selector that will be more selective or add rule that will remove the other. Resources: 

* https://specifishity.com/
* https://www.w3schools.com/cssref/css_selectors.asp
* Example: 
```unset
d-article p {
  text-align: justify;
}

d-article td p {
  text-align: unset
}
```

I'll close this and let you look into all that.

**Closed by cderv** 2021-02-26 08:34 UTC
