### ISSUE TITLE
bullet points not working in distill

### ISSUE THREAD

**Issue by rkbauer** [rstudio/distill#372] opened 2021-05-12 14:43 UTC
Hi,
I just recognized that bullet points are not supported in distill.
Neither with * nor with html code as shown here for RMarkdown
https://monashbioinformaticsplatform.github.io/2017-11-16-open-science-training/topics/rmarkdown.html

**Comment by cderv** [comment] 2021-05-12 16:35
Here is a simple Rmd file with an example of your doc showing that bullet list is working for me. 
I used the Markdown syntax, and also the HTML syntax which should be less usual to use in a Rmd document.

````markdown
---
title: "Bullet list"
output: 
  distill::distill_article: default
---

---
title: "Bullet list"
output: 
  distill::distill_article: default
---

### Today's shopping list:

-   Milk
-   Eggs
-   Cereal
-   Fruit

```{=html}
<h3>Today's shopping list:</h3>
  <ul>
    <li>Milk</li>
    <li>Eggs</li>
    <li>Cereal</li>
    <li>Fruit</li>
  </ul>
```

````

Can you share a reproducible example with your issue ? 

Thank you.

**Comment by rkbauer** [comment] 2021-05-12 19:10
Sorry, was a mistake. I was running * with only one space, which worked with normak RMarkdown, but not in distill and putting the html code not in a chunk.

*  Milk
*  Eggs
*  Cereal
*  Fruit

**Comment by cderv** [comment] 2021-05-12 20:53
I am not quite sure to understand the issue. Sorry. Can you give an example with code ? 

> I was running * with only one space, which worked with normak RMarkdown, but not in distill and putting the html code not in a chunk.

* Having only one space works below
* Not setting the fenced code block raw attributes also works (because Pandoc default as `raw_html` extension)

````markdown
---
title: "Bullet list"
output: 
  distill::distill_article: default
---

### Today's shopping list:

- Milk
- Eggs
- Cereal
- Fruit

<h3>Today's shopping list:</h3>
<ul>
  <li>Milk</li>
  <li>Eggs</li>
  <li>Cereal</li>
  <li>Fruit</li>
</ul>

````

What are you trying exactly ? 

Thanks

**Comment by ayushnoori** [comment] 2021-05-18 23:12
@cderv I am experiencing a perhaps related issue. When you attempt to include an inline code chunk in the bullet point, it does not render as a bullet point. For example:

```
Lorem ipsum:
* `dolor`
* `si`
* `amet`
```

Does not work for me. But the following does work:

```
<p>Lorem ipsum</p>
<ul>
  <li>`dolor`</li>
  <li>`si`</li>
  <li>`amet`</li>
</ul>
```
As a band-aid fix, I am currently using the latter solution with the raw HTML. Thanks for your help!

**Comment by cderv** [comment] 2021-05-19 09:33
@ayushnoori It is just a matter of Markdown syntax: You need a new line before the list items. 

Try with this.

````markdown
---
title: "Bullet list"
output: 
  distill::distill_article: default
---

It will not work if not new line,

Lorem ipsum:
* `dolor`
* `si`
* `amet`

Using code or not

Lorem ipsum:
* dolor
* si
* amet

You need a new line before the list items in Markdown: 

Lorem ipsum:

* `dolor`
* `si`
* `amet`

````

RStudio IDE has now a Visual Markdown Editor that will take care of source formatting for you. You should try it: 
https://rstudio.github.io/visual-markdown-editing/#/

**Comment by ayushnoori** [comment] 2021-05-19 09:42
Thanks for the tip, @cderv! Will test this out.

**Comment by ayushnoori** [comment] 2021-07-26 09:16
@cderv, perhaps this issue can be closed as your comment above addresses the issue (need a new line before the list items)?

**Comment by cderv** [comment] 2021-07-26 10:10
Thanks @ayushnoori ! 

@rkbauer I'll close this as I understand it is a formatting issue in the source but please reopen if you still have issues or questions. thanks!

**Closed by cderv** 2021-07-26 10:10 UTC
