### ISSUE TITLE
Citation format

### ISSUE THREAD

**Issue by JanaJarecki** [rstudio/distill#131] opened 2020-04-21 14:57 UTC
Hi there,

thank you for developing distill for R, it is fantastic!
Quick questions:
If at all -- how can I change the citation style (my field only uses in-text (Author, year) format?
Is there a "theme" to be changed for distilled documents? The font-size is a bit big if using not a Mac. The fonts look great on Mac, but on Windows 10 it's less elegant.

Best
Jana

**Comment by taraskaduk** [comment] 2020-09-29 02:41
Hi @JanaJarecki!

To your first question, my understanding is such that the behavior of `distill` articles shouldn't be any different from an R Markdown document, both of which use Pandoc. Please see more here for details: https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html

Also, my understanding that by default `distill` provides in-text citation in (Author, year) format, and so I'm not sure why does that not work for your needs, but I may be misunderstanding your question.

As for the theme, again, my personal understanding is that `distill` is highly opinionated, and there is not a lot of wiggle room in changing it a whole lot, but you could potentially tweak certain aspects, including font and size with some custom `.css`. See Tom Mock's post as one example: https://themockup.blog/posts/2020-08-01-building-a-blog-with-distill/#customize-appearance

**Comment by jjallaire** [comment] 2020-09-29 09:41
Hi @JanaJarecki, yes, @taraskaduk is correct we use standard pandoc citation handling (that's in the development version of distill, installed via `devtools::install_github("rstudio/distill")`, the version on CRAN still uses the distill framework's handling, which is less flexible. You should be able to customize how citations are presented inline using standard pandoc syntax as described here: https://pandoc.org/MANUAL.html#citations

We will take a look at Windows font sizes and make a change there it it's needed (sounds like it is).

While distill is highly opinionated, it can be customized via CSS (as the article above describes). That said, it is way harder than it should be right now to do this and we need more documentation on which selectors to override. We are working on this now.

**Comment by jjallaire** [comment] 2020-09-29 09:43
Closing this as we now have separate issues tracking the requests here.

**Closed by jjallaire** 2020-09-29 09:43 UTC
Labels: question :question:, style :art:

**Comment by taraskaduk** [comment] 2020-09-29 12:47
FWIW, I think the fact that `distill` is "highly opinionated" is a feature, not a bug. I don't think the initial distill framework was supposed to be customizable. 

My sense is that people are attracted to `distill`'s support for scientific and technical writing, but at the same time need high customization that, say, `blogdown` or `hugodown` provide.

I am wondering if adding "scientific writing" features of `distill` into `blogdown/hugodown` to satisfy this need is a conceptually better approach than forcing `distill` to be less opinionated.

Just a thought.
