### ISSUE TITLE
consider supporting ISO dates

### ISSUE THREAD

**Issue by apreshill** [rstudio/distill#238] opened 2020-12-09 22:05 UTC
😹 
https://twitter.com/RaoOfPhysics/status/1336239836412473344?s=20

**Comment by Selbosh** [comment] 2021-01-26 20:06
Fixed by https://github.com/rstudio/distill/pull/300, at least for the `create_post` function. Not sure if it appears elsewhere

**Comment by cderv** [comment] 2021-02-17 13:22
@apreshill I think the date can already be provided as Year Month Day in the date field. The date field will be parsed as `mdy` or `ymd` if the former does not work.
https://github.com/rstudio/distill/blob/f2571eb9852b59f97006a8c743f28efeb6c1fa25/R/utils.R#L63-L72

We may just need to update the documentation
https://github.com/rstudio/distill/blob/4dc0b80d483b4496d54a64a9129373e82f4ced6c/docs/_common/distill_basics.Rmd#L52

Is there anything else you see to support ISO dates ?

**Comment by cderv** [comment] 2021-02-18 13:19
I think we are all set with both changes now. I'll close this.

**Closed by cderv** 2021-02-18 13:19 UTC

**Comment by cderv** [comment] 2021-02-23 10:10
Duplicate of #27
