### ISSUE TITLE
Cyrillic locals on Windows 10 - can't knit the Rmd.

### ISSUE THREAD

**Issue by alexeilutay** [rstudio/distill#273] opened 2020-12-29 20:08 UTC
Trying to build Distill blog, still at the Welcome stage.
Neither _site.yml, nor the Rmd files contain Cyrillic, but when I knit the Welcome.Rmd, I see this 

Error in read_xml.character(rss_path) :
  Input is not proper UTF-8, indicate encoding !
Bytes: 0xCF 0xED 0x2C 0x20 [9]
Calls: <Anonymous> ... write_feed_xml -> <Anonymous> -> read_xml.character

and multiple warnings like OS reports request to set locale to "en_US.UTF-8" cannot be honored.

I also found the strange non-readable symbols in index.xml in <lastBuildDate> field.

Wondering if there are any patches/settings for this, or so far Distill is not supposed to work on Windows PC with Russian local settings?

I regularly do Rmarkdown reports, setting manually 
Sys.setlocale("LC_CTYPE","russian")
Sys.setlocale("LC_COLLATE","russian")
Sys.setlocale("LC_TIME", "russian")
So apart from Distill, R/Rstudio/Rmarkdown work fine.

Session Info:
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251   
[3] LC_MONETARY=Russian_Russia.1251 LC_NUMERIC=C                   
[5] LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.0.3  htmltools_0.5.0 tools_4.0.3     yaml_2.2.1     
 [5] distill_1.1     rmarkdown_2.5   downlit_0.2.1   knitr_1.30     
 [9] xfun_0.19       digest_0.6.27   rlang_0.4.9     evaluate_0.14

**Comment by larmarange** [comment] 2020-12-31 08:24
Same problem observed on a computer using a French version of Windows. Errors when building the website: locale to "en_US.UTF-8" cannot be honored.

**Comment by jjallaire** [comment] 2020-12-31 11:01
@cderv I'm not sure exactly how to repro this, is your Windows setup such that it might be easy for you to try?

**Comment by larmarange** [comment] 2020-12-31 11:14
Could it be due to the fact that locale values are not the same on Linux and Windows?

On Windows, `Sys.setlocale(locale = "en_US.UTF-8")` will fail. The correct syntax is `Sys.setlocale(locale = "English")`.

This is indicated in the examples of `Sys.setlocale()` documentation.

**Comment by larmarange** [comment] 2020-12-31 11:19
Maybe relevant to explore this line of code: https://github.com/rstudio/distill/blob/78b7e68e663fd68bc271d1cbc018a2b5a110887b/R/utils.R#L121

**Comment by jjallaire** [comment] 2020-12-31 11:46
So you think that if we changed the line to this:

```r
new = c("LC_TIME" = "English"),
```

Then everything would work as expected?

Are you in a position to try this out on your system?

**Comment by cderv** [comment] 2020-12-31 15:24
@jjallaire I can confirm that on windows `Sys.setlocale("LC_TIME", locale = "en_US.UTF-8")` won't work as this is not one of available locale.

Using `"English"` instead will work on Windows.
``` r
as.character(Sys.time(), format = "%a, %d %b %Y %H:%M:%S %z", tz = "UTC")
#> [1] "jeu., 31 déc. 2020 15:11:55 +0000"

withr::with_locale(
  new = c("LC_TIME" = "English"),
  as.character(Sys.time(), format = "%a, %d %b %Y %H:%M:%S %z", tz = "UTC")
)
#> [1] "Thu, 31 Dec 2020 15:11:55 +0000"
```

<sup>Created on 2020-12-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

However, it won't work on other system. Ex. on Ubuntu
```r
❯ Sys.setlocale("LC_TIME", locale = "English")
[1] ""
Warning message:
In Sys.setlocale("LC_TIME", locale = "English") :
  OS reports request to set locale to "English" cannot be honored
```
You'll need a conditional on the OS here.

However, I don't think this is related to the `read_xml.character` error. I'll try to replicate on my Windows system as soon as possible.

**Comment by cderv** [comment] 2021-01-04 11:12
I managed to reproduce this error with xml and it is in fact caused by this date format. 

I think the xml file written is assumed to be UTF8, and encoding is indicated as such, but in fact it contains non UTF8 character. For example, I have this when I open the file: 
```
<pubDate>mer., 30 d?c. 2020 00:00:00 +0000</pubDate>
```
and it fact, if I open the file as ANSI (windows default) and not UTF8, it will shown ok: 
```
<pubDate>mer., 30 déc. 2020 00:00:00 +0000</pubDate>
```

So I think the previous fix will correct this issue, but it may only hide it. It is possible that the xml files written will be encoded as UTF8 but does no contains UTF8 character. However, this published date field maybe the only one. I did some quick test with other fields from the YAML header but as Rmd files must be UTF8 now, they are encoded ok when parsed by YAML. It seems it will only happens with any character created inside R on Windows, which will be using Native encoding (Latin 1 in my case)

See this minimal reproducible of the issue on Windows with non UTF8 default encoding 

````r
> library(xml2)
> xml <- xml_new_document()
> child <- xml_add_child(xml, "test")
> text <- "Décembre"
> Encoding(text)
[1] "latin1"
> xml_text(child) <- text
> tmp_xml <- tempfile(fileext = ".xml")
> write_xml(xml, tmp_xml)
NULL
> read_xml(tmp_xml)
Error in read_xml.character(tmp_xml) : 
  Input is not proper UTF-8, indicate encoding !
Bytes: 0xE9 0x63 0x65 0x6D [9]
Run `rlang::last_error()` to see where the error occurred.
> text2 <- iconv(text, to = "UTF-8")
> xml_text(child) <- text2
> write_xml(xml, tmp_xml)
NULL
> read_xml(tmp_xml)
{xml_document}
<test>
> xml_find_all(read_xml(tmp_xml), "/test")
{xml_nodeset (1)}
[1] <test>Décembre</test>
```

**Comment by jjallaire** [comment] 2021-01-04 11:25
Thanks for sorting that out! So do you recommend that we do anything else here or is the previous fix sufficient?

**Comment by jjallaire** [comment] 2021-01-04 12:29
Closing this for now, @cderv LMK if we should re-open this or open another related issue.

**Closed by jjallaire** 2021-01-04 12:29 UTC

**Comment by cderv** [comment] 2021-01-04 12:58
I took the time to look more intot `write_feed_xml` and `write_sitemap_xml`. I don't see any other text field created that could have this issue. All the other field comes from YAML (either a yaml file or a yaml header), and the tools (**rmarkdown** and **yaml**) assumes the content to be UTF-8 already. 

If we were to do something it would be to insure to encode everything that could contains special character as UTF8 before writing the xml file. I don't think we need to add this for now. Dealing with encoding is always tricky.

In any case if I missed something we know the **xml2** error and could fix quickly.

**Comment by jjallaire** [comment] 2021-01-04 13:10
Okay, thanks. I'll leave this alone for now then.

**Comment by alexeilutay** [comment] 2021-01-06 12:34
Many thanks, guys! I re-installed the package (found the new code) and it seems to be working.
