### ISSUE TITLE
`cat`ed headings missing in table of content

### ISSUE THREAD

**Issue by joundso** [rstudio/distill#438] opened 2022-01-28 08:53 UTC
## The problem
Creating headings by hand will make display them in the table bof content (toc) but if they are created automatically via `cat("\n## Heading\n")`, they don't. Also the 'link' icon does not apper next to these programmatically created headings.
Is this a bug or a feature? Maybe I am missing something important?
In any case, I am grateful for any help! Many thanks in advance!

## Code to reproduce

````rmd
---
title: "Document title"
output:
  distill::distill_article:
    toc: yes
    toc_depth: 6
    toc_float: true
  # pdf_document:
  #   number_sections: yes
  #   toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
show_cated_headings <- TRUE
```


# Test 1
## Subsection 1

# Test 2
## Subsection 2

# Test 3


```{r, results='asis', echo=FALSE}
for (Species in levels(iris$Species)) {
  if (show_cated_headings) {
    cat('\n##', Species, '\n')
  }
  p <- ggplot2::ggplot(iris[iris$Species == Species, ],
                       ggplot2::aes(x = Sepal.Length, y = Sepal.Width)) +
    ggplot2::geom_point()
  print(p)
  cat("\n")
}
```
````

## My session info

``` r
sessioninfo::session_info()
#> Warning in system("timedatectl", intern = TRUE): running command 'timedatectl'
#> had status 1
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       Ubuntu 20.04.3 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Etc/UTC
#>  date     2022-01-28
#>  pandoc   2.14.0.3 @ /usr/lib/rstudio-server/bin/pandoc/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  backports     1.4.1   2021-12-13 [1] CRAN (R 4.1.2)
#>  cli           3.1.1   2022-01-20 [1] CRAN (R 4.1.2)
#>  crayon        1.4.2   2021-10-29 [1] CRAN (R 4.1.2)
#>  digest        0.6.29  2021-12-01 [1] CRAN (R 4.1.2)
#>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.2)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.1.2)
#>  fansi         1.0.2   2022-01-14 [1] CRAN (R 4.1.2)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.2)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.1.2)
#>  glue          1.6.1   2022-01-22 [1] CRAN (R 4.1.2)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.1.2)
#>  htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.1.2)
#>  knitr         1.37    2021-12-16 [1] CRAN (R 4.1.2)
#>  lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.1.2)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.2)
#>  pillar        1.6.4   2021-10-18 [1] CRAN (R 4.1.2)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.2)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.1.2)
#>  R.cache       0.15.0  2021-04-30 [1] CRAN (R 4.1.2)
#>  R.methodsS3   1.8.1   2020-08-26 [1] CRAN (R 4.1.2)
#>  R.oo          1.24.0  2020-08-26 [1] CRAN (R 4.1.2)
#>  R.utils       2.11.0  2021-09-26 [1] CRAN (R 4.1.2)
#>  reprex        2.0.1   2021-08-05 [1] CRAN (R 4.1.2)
#>  rlang         0.4.12  2021-10-18 [1] CRAN (R 4.1.2)
#>  rmarkdown     2.11    2021-09-14 [1] CRAN (R 4.1.2)
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.2)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.1.2)
#>  stringi       1.7.6   2021-11-29 [1] CRAN (R 4.1.2)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.1.2)
#>  styler        1.6.2   2021-09-23 [1] CRAN (R 4.1.2)
#>  tibble        3.1.6   2021-11-07 [1] CRAN (R 4.1.2)
#>  utf8          1.2.2   2021-07-24 [1] CRAN (R 4.1.2)
#>  vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.1.2)
#>  withr         2.4.3   2021-11-30 [1] CRAN (R 4.1.2)
#>  xfun          0.29    2021-12-14 [1] CRAN (R 4.1.2)
#>  yaml          2.2.2   2022-01-25 [1] CRAN (R 4.1.2)
#> 
#>  [1] /usr/local/lib/R/site-library
#>  [2] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

### Missing haeding in toc

![Missing haeding in toc](https://user-images.githubusercontent.com/56686638/151517391-28f93e56-2a1b-46df-ac13-21b6020267cf.png)

### Missing 'link' icon next to programmatically created heading

![Missing 'link' icon next to programmatically created heading](https://user-images.githubusercontent.com/56686638/151517261-b05cd778-0235-4671-bc2a-c13d7aa86224.png)

## Further stuff

I tried using [this gist](https://gist.github.com/gadenbuie/c83e078bf8c81b035e32c3fc0cf04ee8) which unfortunately was unsuccessful.

**Comment by cderv** [comment] 2022-02-02 11:32
Unfortunately I did not remember there was a duplicate of this issue. So I spend another few time to look into this. 

This is the same as https://github.com/rstudio/distill/issues/367 - possibly a Pandoc bugs but not sure. 

For now you can use `md_extensions: -native_divs`

I'll close this issue in favor of this other.

**Comment by cderv** [comment] 2022-02-02 11:32
Duplicate of #367

**Closed by cderv** 2022-02-02 11:32 UTC

**Comment by joundso** [comment] 2022-02-02 11:49
@cderv Thank you very much for your time and the quick solution! I'm sorry that I haven't found the other issue although I had been looking for one. So: Double thanks! 👍
